<?php
$Visit=array(
1=>$Fecha1D = date('d-m-Y',strtotime($Fecha.'+1 days')),
2=>$Fecha2D = date('d-m-Y',strtotime($Fecha.'+2 days')),
3=>$Fecha3D = date('d-m-Y',strtotime($Fecha.'+3 days')),
4=>$Fecha4D = date('d-m-Y',strtotime($Fecha.'+4 days')),
5=>$Fecha5D = date('d-m-Y',strtotime($Fecha.'+5 days')),
6=>$Fecha6D = date('d-m-Y',strtotime($Fecha.'+6 days')),
7=>$Fecha7D = date('d-m-Y',strtotime($Fecha.'+7 days')),
8=>$Fecha8D = date('d-m-Y',strtotime($Fecha.'+8 days')),
9=>$Fecha9D = date('d-m-Y',strtotime($Fecha.'+9 days')),
10=>$Fecha10D = date('d-m-Y',strtotime($Fecha.'+10 days')),
11=>$Fecha11D = date('d-m-Y',strtotime($Fecha.'+11 days')),
12=>$Fecha12D = date('d-m-Y',strtotime($Fecha.'+12 days')),
13=>$Fecha13D = date('d-m-Y',strtotime($Fecha.'+13 days')),
14=>$Fecha14D = date('d-m-Y',strtotime($Fecha.'+14 days')),
15=>$Fecha15D = date('d-m-Y',strtotime($Fecha.'+15 days')),
16=>$Fecha1D = date('d-m-Y',strtotime($Fecha.'+16 days')),
17=>$Fecha2D = date('d-m-Y',strtotime($Fecha.'+17 days')),
18=>$Fecha3D = date('d-m-Y',strtotime($Fecha.'+18 days')),
19=>$Fecha4D = date('d-m-Y',strtotime($Fecha.'+19 days')),
20=>$Fecha5D = date('d-m-Y',strtotime($Fecha.'+20 days')),
21=>$Fecha6D = date('d-m-Y',strtotime($Fecha.'+21 days')),
22=>$Fecha7D = date('d-m-Y',strtotime($Fecha.'+22 days')),
23=>$Fecha8D = date('d-m-Y',strtotime($Fecha.'+23 days')),
24=>$Fecha9D = date('d-m-Y',strtotime($Fecha.'+24 days')),
25=>$Fecha10D = date('d-m-Y',strtotime($Fecha.'+25 days')),
26=>$Fecha11D = date('d-m-Y',strtotime($Fecha.'+26 days')),
27=>$Fecha12D = date('d-m-Y',strtotime($Fecha.'+27 days')),
28=>$Fecha13D = date('d-m-Y',strtotime($Fecha.'+28 days')),
29=>$Fecha14D = date('d-m-Y',strtotime($Fecha.'+29 days')),
30=>$Fecha15D = date('d-m-Y',strtotime($Fecha.'+30 days')),
);
?>