<?php
$IdCli=$result->IdCli;
$NameCli=$result->NameCli;
$Barrio=$result->Barrio;
$Direccion=$result->Direccion;
$TelCli=$result->TelCli;
$Frec=$result->Frecuencia;
$Visita=$result->Visita;
$hour=$result->hour;
$DAM400g5=$result->AM400g5;
$DAM550g5=$result->AM550g5;
$DAM700g10=$result->AM700g10;
$DAM800g20=$result->AM800g20;
$d_masax1k=$result->masax1k;
$IdVendedor=$result->IdVendedor;
$NameVendedor=$result->NameVendedor;
$Pedido=$result->Pedido;
$RutaC=$result->Ruta;
?>