<?php
$id_us=$result->id_us;
$name_us=$result->name_us;
$email_us=$result->email_us;
$tel_us=$result->tel_us;
$key_us=$result->key_us;
$profile=$result->profile;
$customer=$result->customer;
$OD14x5=$result->OD14x5;
$OD16x5=$result->OD16x5;
$OMinx20=$result->OMinx20;
$o_masax1k=$result->o_masax1k;
?>