<?php
$id_us=$result->IdUs;
$name_us=$result->NameUs;
$email_us=$result->EmailUs;
$tel_us=$result->TelUs;
$key_us=$result->ClaveUs;
$profile=$result->Perfil;
$customer=$result->ClienteActual;
$OD14x5=$result->OD14x5;
$OD16x5=$result->OD16x5;
$OMinx20=$result->OMinx20;
?>